/**
 * report.ts — tRPC router for Automated Report Schedules
 *
 * Procedures:
 *  report.createSchedule  — create a daily report schedule + heartbeat cron
 *  report.listSchedules   — list user's schedules
 *  report.updateSchedule  — update schedule config or toggle active
 *  report.deleteSchedule  — delete schedule + cancel heartbeat
 *  report.getLogs         — get report send history
 *  report.sendNow         — manually trigger a report send
 */

import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { parse as parseCookie } from "cookie";
import { COOKIE_NAME } from "@shared/const";
import { protectedProcedure, router } from "../_core/trpc";
import {
  createReportSchedule,
  getReportSchedulesByUserId,
  getReportScheduleById,
  updateReportSchedule,
  deleteReportSchedule,
  updateReportScheduleCronUid,
  markReportScheduleRun,
  createReportLog,
  getReportLogsByUserId,
  getFacebookToken,
  getNotificationSettings,
} from "../db";
import { createHeartbeatJob, deleteHeartbeatJob, updateHeartbeatJob } from "../_core/heartbeat";
import { fetchReportData, generateExcelReport, generatePdfReport } from "../reportGenerator";
import { sendLineNotification, sendEmailNotification } from "../alertEngine";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getSessionToken(cookieHeader: string): string {
  return parseCookie(cookieHeader ?? "")[COOKIE_NAME] ?? "";
}

async function runReportForSchedule(
  scheduleId: number,
  userId: number,
  adAccountId: string,
  adAccountName: string,
  reportFormat: "pdf" | "excel" | "both",
  notifyLine: number,
  notifyEmail: number
) {
  // Get Meta access token
  const tokenRow = await getFacebookToken(userId);
  if (!tokenRow?.accessToken) {
    throw new Error("No Meta access token found for user");
  }

  // Fetch 7-day data from Meta API
  const reportData = await fetchReportData(tokenRow.accessToken, adAccountId, 7);
  reportData.adAccountName = adAccountName || adAccountId;

  let pdfKey: string | undefined;
  let excelKey: string | undefined;
  let pdfUrl: string | undefined;
  let excelUrl: string | undefined;

  // Generate files
  if (reportFormat === "pdf" || reportFormat === "both") {
    const result = await generatePdfReport(reportData, userId);
    pdfKey = result.key;
    pdfUrl = result.url;
  }

  if (reportFormat === "excel" || reportFormat === "both") {
    const result = await generateExcelReport(reportData, userId);
    excelKey = result.key;
    excelUrl = result.url;
  }

  // Get notification settings
  const notifSettings = await getNotificationSettings(userId);
  let lineNotified = 0;
  let emailNotified = 0;

  const reportSummary = [
    `📊 Facebook Ads Daily Report`,
    `📅 ${reportData.dateFrom} to ${reportData.dateTo}`,
    `💰 Spend: ฿${reportData.totalSpend.toFixed(2)}`,
    `👁 Impressions: ${reportData.totalImpressions.toLocaleString()}`,
    `🖱 Clicks: ${reportData.totalClicks.toLocaleString()}`,
    `🎯 Leads: ${reportData.totalLeads}`,
    `🛒 Purchases: ${reportData.totalPurchases}`,
    `📈 Avg ROAS: ${reportData.avgRoas.toFixed(2)}x`,
    pdfUrl ? `\n📄 PDF: ${process.env.VITE_APP_ID ? `[Download]` : pdfUrl}` : "",
    excelUrl ? `📊 Excel: ${excelUrl}` : "",
  ].filter(Boolean).join("\n");

  // Send LINE notification
  if (notifyLine && notifSettings?.lineToken) {
    const ok = await sendLineNotification(notifSettings.lineToken, reportSummary);
    if (ok) lineNotified = 1;
  }

  // Send email notification
  if (notifyEmail && notifSettings?.notifyEmail) {
    const emailBody = reportSummary + "\n\nReport generated by AI Facebook Ads Guide.";
    const ok = await sendEmailNotification(
      notifSettings.notifyEmail,
      `Facebook Ads Daily Report — ${reportData.dateFrom}`,
      emailBody
    );
    if (ok) emailNotified = 1;
  }

  // Log the report
  await createReportLog({
    scheduleId,
    userId,
    adAccountId,
    reportFormat,
    pdfStorageKey: pdfKey ?? null,
    excelStorageKey: excelKey ?? null,
    lineNotified,
    emailNotified,
    totalSpend: reportData.totalSpend,
    totalImpressions: reportData.totalImpressions,
    totalClicks: reportData.totalClicks,
    totalLeads: reportData.totalLeads,
    totalPurchases: reportData.totalPurchases,
    avgRoas: reportData.avgRoas,
    status: "success",
  });

  await markReportScheduleRun(scheduleId);

  return {
    pdfUrl,
    excelUrl,
    summary: reportData,
    lineNotified: lineNotified === 1,
    emailNotified: emailNotified === 1,
  };
}

// ─── Router ───────────────────────────────────────────────────────────────────

export const reportRouter = router({
  /**
   * Create a new report schedule with daily heartbeat cron (01:00 UTC = 08:00 ICT)
   */
  createSchedule: protectedProcedure
    .input(z.object({
      name: z.string().min(1).max(255),
      adAccountId: z.string().min(1),
      adAccountName: z.string().optional(),
      reportFormat: z.enum(["pdf", "excel", "both"]).default("both"),
      notifyLine: z.boolean().default(true),
      notifyEmail: z.boolean().default(false),
      // Optional custom cron (6-field UTC). Default: daily 01:00 UTC = 08:00 ICT
      cronExpression: z.string().default("0 0 1 * * *"),
    }))
    .mutation(async ({ ctx, input }) => {
      const userId = ctx.user.id;

      // Create DB record first
      const result = await createReportSchedule({
        userId,
        name: input.name,
        adAccountId: input.adAccountId,
        adAccountName: input.adAccountName ?? input.adAccountId,
        reportFormat: input.reportFormat,
        notifyLine: input.notifyLine ? 1 : 0,
        notifyEmail: input.notifyEmail ? 1 : 0,
        cronExpression: input.cronExpression,
        isActive: 1,
      });

      const scheduleId = (result as unknown as [{ insertId: number }])[0]?.insertId;
      if (!scheduleId) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Failed to create schedule" });

      // Schedule heartbeat cron
      const sessionToken = getSessionToken(ctx.req.headers.cookie ?? "");
      try {
        const job = await createHeartbeatJob({
          name: `report-schedule-${scheduleId}`,
          cron: input.cronExpression,
          path: "/api/scheduled/send-report",
          payload: { scheduleId },
          description: `Daily report: ${input.name}`,
        }, sessionToken);

        await updateReportScheduleCronUid(scheduleId, job.taskUid);
      } catch (err) {
        console.warn("[ReportRouter] Failed to schedule heartbeat:", err);
        // Non-fatal: schedule is saved, cron will be set up after deploy
      }

      return { success: true, scheduleId };
    }),

  /**
   * List all report schedules for the current user
   */
  listSchedules: protectedProcedure
    .query(async ({ ctx }) => {
      return getReportSchedulesByUserId(ctx.user.id);
    }),

  /**
   * Update a report schedule (format, channels, toggle active)
   */
  updateSchedule: protectedProcedure
    .input(z.object({
      id: z.number(),
      name: z.string().min(1).max(255).optional(),
      reportFormat: z.enum(["pdf", "excel", "both"]).optional(),
      notifyLine: z.boolean().optional(),
      notifyEmail: z.boolean().optional(),
      isActive: z.boolean().optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const { id, ...updates } = input;
      const schedule = await getReportScheduleById(id, ctx.user.id);
      if (!schedule) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });

      const dbUpdates: Record<string, unknown> = {};
      if (updates.name !== undefined) dbUpdates.name = updates.name;
      if (updates.reportFormat !== undefined) dbUpdates.reportFormat = updates.reportFormat;
      if (updates.notifyLine !== undefined) dbUpdates.notifyLine = updates.notifyLine ? 1 : 0;
      if (updates.notifyEmail !== undefined) dbUpdates.notifyEmail = updates.notifyEmail ? 1 : 0;
      if (updates.isActive !== undefined) dbUpdates.isActive = updates.isActive ? 1 : 0;

      await updateReportSchedule(id, ctx.user.id, dbUpdates);

      // Pause/resume heartbeat if toggling active
      if (updates.isActive !== undefined && schedule.scheduleCronTaskUid) {
        const sessionToken = getSessionToken(ctx.req.headers.cookie ?? "");
        try {
          await updateHeartbeatJob(schedule.scheduleCronTaskUid, { enable: updates.isActive }, sessionToken);
        } catch (err) {
          console.warn("[ReportRouter] Failed to update heartbeat:", err);
        }
      }

      return { success: true };
    }),

  /**
   * Delete a report schedule and cancel its heartbeat cron
   */
  deleteSchedule: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const schedule = await getReportScheduleById(input.id, ctx.user.id);
      if (!schedule) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });

      // Cancel heartbeat
      if (schedule.scheduleCronTaskUid) {
        const sessionToken = getSessionToken(ctx.req.headers.cookie ?? "");
        try {
          await deleteHeartbeatJob(schedule.scheduleCronTaskUid, sessionToken);
        } catch (err) {
          console.warn("[ReportRouter] Failed to delete heartbeat:", err);
        }
      }

      await deleteReportSchedule(input.id, ctx.user.id);
      return { success: true };
    }),

  /**
   * Get report send history for the current user
   */
  getLogs: protectedProcedure
    .input(z.object({ limit: z.number().min(1).max(100).default(30) }))
    .query(async ({ ctx, input }) => {
      return getReportLogsByUserId(ctx.user.id, input.limit);
    }),

  /**
   * Manually trigger a report send now
   */
  sendNow: protectedProcedure
    .input(z.object({ id: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const schedule = await getReportScheduleById(input.id, ctx.user.id);
      if (!schedule) throw new TRPCError({ code: "NOT_FOUND", message: "Schedule not found" });

      try {
        const result = await runReportForSchedule(
          schedule.id,
          ctx.user.id,
          schedule.adAccountId,
          schedule.adAccountName ?? schedule.adAccountId,
          schedule.reportFormat,
          schedule.notifyLine,
          schedule.notifyEmail
        );
        return { success: true, ...result };
      } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        await createReportLog({
          scheduleId: schedule.id,
          userId: ctx.user.id,
          adAccountId: schedule.adAccountId,
          reportFormat: schedule.reportFormat,
          lineNotified: 0,
          emailNotified: 0,
          status: "failed",
          errorMessage: errorMsg,
        });
        throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: errorMsg });
      }
    }),
});

// ─── Heartbeat handler (called by Express) ────────────────────────────────────

export async function handleSendReportCron(taskUid: string) {
  const { getReportScheduleByCronUid } = await import("../db");
  const schedule = await getReportScheduleByCronUid(taskUid);
  if (!schedule) return { ok: true, skipped: "orphan" };
  if (!schedule.isActive) return { ok: true, skipped: "inactive" };

  try {
    await runReportForSchedule(
      schedule.id,
      schedule.userId,
      schedule.adAccountId,
      schedule.adAccountName ?? schedule.adAccountId,
      schedule.reportFormat,
      schedule.notifyLine,
      schedule.notifyEmail
    );
    return { ok: true };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    await createReportLog({
      scheduleId: schedule.id,
      userId: schedule.userId,
      adAccountId: schedule.adAccountId,
      reportFormat: schedule.reportFormat,
      lineNotified: 0,
      emailNotified: 0,
      status: "failed",
      errorMessage: errorMsg,
    });
    throw err;
  }
}
