CREATE TABLE `creative_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`adAccountId` varchar(64) NOT NULL,
	`dateRange` varchar(10) NOT NULL,
	`adId` varchar(64) NOT NULL,
	`adName` varchar(512) NOT NULL,
	`adsetId` varchar(64),
	`adsetName` varchar(512),
	`campaignId` varchar(64),
	`campaignName` varchar(512),
	`thumbnailUrl` text,
	`videoId` varchar(64),
	`creativeType` enum('image','video','carousel','unknown') DEFAULT 'unknown',
	`spend` float DEFAULT 0,
	`impressions` bigint DEFAULT 0,
	`clicks` bigint DEFAULT 0,
	`ctr` float DEFAULT 0,
	`cpc` float DEFAULT 0,
	`cpa` float DEFAULT 0,
	`roas` float DEFAULT 0,
	`conversions` bigint DEFAULT 0,
	`videoThruPlays` bigint DEFAULT 0,
	`video3SecPlays` bigint DEFAULT 0,
	`videoAvgPlayTime` float DEFAULT 0,
	`fetchedAt` bigint NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `creative_cache_id` PRIMARY KEY(`id`)
);
